### ISSUE TITLE
Pie Navigation make system interface crash

### ISSUE THREAD

**Issue by Xhelliom** [ResurrectionRemix-Devices/device_oneplus_oneplus3#1]
in RR-OS settings, ticking "Pie" make system interface crash.
Had to Full wipe and reflash OS

**Comment by varund7726** [comment]
Use English language for now .we will fix this soon.don't open issues on gjthub in future

**Comment by Xhelliom** [comment]
Thanks for the answer, sorry about thath

**Comment by le1nvisible** [comment]
Hi all, I've got the same problem, ticked pie and the system crashed. Now I am unable to get back to recovery mode (tried to reach trough pressing vol-up + power). Do you guys know a trick how to get back into recovery?
I'm using a Galaxy S7 (herolte).
